language: java
jdk:
- openjdk11

sudo: false
dist: trusty

cache:
  directories:
  - $HOME/.m2
  
addons:
  sonarcloud:
    organization: "mbirkmann-github"
    token:
      secure: ${SONAR_TOKEN}
      
script:
  - mvn clean install

after_success:
  - mvn clean test jacoco:report coveralls:report sonar:sonar
