language: java
jdk:
- openjdk11

sudo: false
dist: trusty

addons:
  sonarcloud:
    organization: "mbirkmann-github"
    token:
      secure: SONAR_TOKEN
      
script:
- mvn clean install

cache:
  directories:
  - $HOME/.m2

after_success:
  - mvn clean test jacoco:report coveralls:report
