language: java
jdk:
- openjdk11

sudo: false
dist: trusty

addons:
  sonarcloud:
    organization: "mbirkmann-github"
    token:
      SONAR_TOKEN
      
script:
- mvn clean install coveralls:report sonar:sonar

cache:
  directories:
  - $HOME/.m2
